### ISSUE TITLE
Does it work on Linux

### ISSUE THREAD

**Issue by ScripDid** [Nike-Inc/gimme-aws-creds#59]
Cannot get it work on Ubuntu 16.04 LTS neither on cygwin
But works fine on Windows 10

Error :
me@my-ubu1604lts:~/gimme-aws-creds/bin$ ./gimme-aws-creds
Traceback (most recent call last):
  File "./gimme-aws-creds", line 13, in <module>
    from gimme_aws_creds.main import GimmeAWSCreds
ImportError: No module named 'gimme_aws_creds'

**Comment by anners** [comment]
If you installed gimme-aws-creds with pip3 or python3 setup.py install, the executable should have been installed as /usr/local/bin/gimme-aws-creds. Can you try running it from there and see if that fixes the error?

**Comment by Sector95** [comment]
Dropping the `./` from your execution command will cause the OS to search your path for the executable, instead of trying to execute from the local folder.

**Comment by ScripDid** [comment]
Hi,

I ran : python3 setup.py install

then I got : 

...
Installed /usr/local/lib/python3.5/dist-packages/python_dateutil-2.7.2-py3.5.egg
Searching for cryptography
Reading https://pypi.python.org/simple/cryptography/
Best match: cryptography 2.2.2
Downloading https://files.pythonhosted.org/packages/ec/b2/faa78c1ab928d2b2c634c8b41ff1181f0abdd9adf 9193211bd606ffa57e2/cryptography-2.2.2.tar.gz#sha256=9fc295bf69130a342e7a19a39d7bbeb15c0bcaabc7382e c33ef3b2b7d18d2f63
Processing cryptography-2.2.2.tar.gz
Writing /tmp/easy_install-yrz9i9tk/cryptography-2.2.2/setup.cfg
Running cryptography-2.2.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-yrz9i9tk/cryptography -2.2.2/egg-dist-tmp-ghj0n4ki
c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

After installing libffi-dev on Ubuntu using apt (libffi-devel for RHEL) and I ran again

I got this : 

...
Installed /tmp/easy_install-rh9p9rys/cryptography-2.2.2/.eggs/pycparser-2.18-py3.5.egg
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '*' found under directory 'vectors'
build/temp.linux-x86_64-3.5/_openssl.c:493:30: fatal error: openssl/opensslv.h: No such file or directory
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Then I apt libssl-dev, ran pip3 install and could see many warnings till got : 

...
Installed /usr/local/lib/python3.5/dist-packages/cryptography-2.2.2-py3.5-linux-x86_64.egg
Searching for jeepney
Reading https://pypi.python.org/simple/jeepney/
Best match: jeepney 0.3.1
Downloading https://files.pythonhosted.org/packages/18/17/7dbc70bc13dc9c8ba8c9b25fbc8b75dffb6bc7e56c3d7cecd87e6b563e5f/jeepney-0.3.1.tar.gz#sha256=a6f2aa72e61660248d4d524dfccb6405f17c693b69af5d60dd7f2bab807d907e
Processing jeepney-0.3.1.tar.gz
Writing /tmp/easy_install-rxzl1zhl/jeepney-0.3.1/setup.cfg
Running jeepney-0.3.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-rxzl1zhl/jeepney-0.3.1/egg-dist-tmp-58z4flvf
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
error: Setup script exited with error: can't copy 'jeepney/integrate': doesn't exist or not a regular file

So I ran : 
sudo pip install jeepney
sudo pip install cryptography
sudo pip install docutils

And finally I could get it work.

I think you should include more requirements from my experience : trying to run gimme-aws-creds from a fresh Ubuntu server (apt-g update && apt-g upgrade done before cloning gimme-aws-creds)

Thanks,

**Comment by Sector95** [comment]
I noticed this yesterday on a fresh Ubuntu 16.04 installation, except in my case all I needed was `libssl-dev`.

We can do more testing, but the dependency chain should be taking care of all the dependencies.  We don't directly reference jeepney, cryptography, or docutils in our code.
